#page title
page_title                                :

# App Info
ios_app_id                                : 1289764391

appstore_link                             : https://itunes.apple.com/jp/app/nowplaying-%E8%B5%B7%E5%8B%95%E3%81%99%E3%82%8B%E3%81%A0%E3%81%91%E3%81%A7%E3%83%84%E3%82%A4%E3%83%BC%E3%83%88/id1289764391?mt=8

app_icon                                  : assets/appicon.jpg
app_name                                  : NowPlaying
app_price                                 : ç„¡æ–™ ( ä¸€éƒ¨ã‚³ãƒ³ãƒ†ãƒ³ãƒ„æœ‰æ–™ )
app_description                           : ä»Šèã„ã¦ã„ã‚‹éŸ³æ¥½ã‚’Twitterã¨ãƒã‚¹ãƒˆãƒ‰ãƒ³ã«ã‚·ã‚§ã‚¢ã—ã‚ˆã†ï¼

enable_smart_app_banner                   : true



# Information About Yourself
your_name                                 : Yuya Oka
your_link                                 : https://nnsnodnb.github.io
your_city                                 : Kanagawa, Japan
email_address                             : nnsnodnb@gmail.com
facebook_username                         : nnsnodnb
instagram_username                        : nnsnodnb
twitter_username                          : nnsnodnb
github_username                           : nnsnodnb



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Twitterã‚·ã‚§ã‚¢
    description                           : è‡ªåˆ†è‡ªèº«ã§ã‚·ã‚§ã‚¢ã™ã‚‹ã“ã¨ã‚‚å¯èƒ½ã§ã™ãŒã€1å›é™ã‚Šã®è³¼å…¥ã§è‡ªå‹•çš„ã«ãƒ„ã‚¤ãƒ¼ãƒˆã™ã‚‹æ©Ÿèƒ½ã‚‚ã‚ã‚Šï¼
    fontawesome_icon_name                 : twitter
    
  - title                                 : Mastodonã‚·ã‚§ã‚¢
    description                           : è‡ªåˆ†è‡ªèº«ã§ã‚·ã‚§ã‚¢ã™ã‚‹ã“ã¨ã‚‚ã€è‡ªå‹•ã§ãƒˆã‚¥ãƒ¼ãƒˆã™ã‚‹æ©Ÿèƒ½ã‚ã‚Šï¼ï¼ˆç¾åœ¨ã®æ™‚ç‚¹ã§ã¯ç„¡æ–™ï¼ï¼ï¼‰
    fontawesome_icon_name                 : mastodon

  - title                                 : ã‚ãªãŸã‚‚é–‹ç™ºã«å‚åŠ ğŸ’»
    description                           : æ°—ãŒç‹‚ã£ã¦ã—ã¾ã£ãŸã®ã‹ã€GitHubã«ã¦ã‚½ãƒ¼ã‚¹ã‚³ãƒ¼ãƒ‰ã‚’å…¬é–‹ã—ã¦ã„ã¾ã™ï¼ãœã²Pull Requestç­‰ã‚’ğŸ˜
    fontawesome_icon_name                 : file-code

  - title                                 : çš†æ§˜ã®ãŠã‹ã’ã§ãƒ¦ãƒ¼ã‚¶æ•°7000äººè¶…ãˆğŸ¤©ğŸ¤©
    description                           : æœ¬å½“ã«ã„ã¤ã‚‚ä½¿ã£ã¦ãã‚Œã¦ã‚ã‚ŠãŒã¨ã†ã”ã–ã„ã¾ã™ğŸ™‡â€â™‚ï¸ (æœˆé–“ä½¿ç”¨ãƒ¦ãƒ¼ã‚¶æ•°ï¼š2900äºº)
    fontawesome_icon_name                 : user


# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.jpg
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : white                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME
